version: "3"
services:
  app:
    container_name: app
    build:
      context: .
    depends_on:
      - db
      - activemq
    environment:
      - DB_URL=jdbc:postgresql://db:5432/ethereum_wallet
      - DB_USER=root
      - DB_PASS=root
      - ACTIVEMQ_BROKER_URL=tcp://activemq:61616
      - ACTIVEMQ_USER=root
      - ACTIVEMQ_PASSWORD=root
    ports:
      - "8080:8080"
    restart: always
  db:
    container_name: db
    image: postgres:14
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ethereum_wallet
    ports:
      - "5432:5432"
    restart: always
  activemq:
    container_name: activemq
    image: webcenter/activemq:5.14.3
    ports:
      - "8162:8161"
      - "61616:61616"
    environment:
      - ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true
      - ACTIVEMQ_ADMIN_LOGIN=root
      - ACTIVEMQ_ADMIN_PASSWORD=root
    restart: always